#!/bin/bash

nohup /usr/lib/postgresql/9.3/bin/postgres -D /var/lib/postgresql/9.3/main -c config_file=/etc/postgresql/9.3/main/postgresql.conf &

sh parser/updateXML.sh

echo "Database Migrations"
python manage.py makemigrations dblpGraphs
python manage.py migrate dblpGraphs

python manage.py makemigrations
python manage.py migrate
echo "Database Read"
python populate_db.py
